
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "27542:5432"
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_REALM_NAME: smr-shop
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "7777:8080"
    volumes:
      - auth-volume:/opt/keycloak/data/

volumes:
  keycloak-volume:
  keycloak-postgres-volume: