version: '3.8'

services:
  shop-service-postgres:
    container_name: shop-service-postgres
    image: postgres:16
    ports:
      - "9115:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9115
    volumes:
      - shop-volume:/var/lib/postgresql/data
volumes:
  shop-volume:
