server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      locator:
        enabled: true
    config:
      enabled: false

    gateway:
      routes:

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/1.0/cart/**, /v3/api-docs/cart

        - id: category-brand-service
          uri: lb://category-brand-service
          predicates:
            - Path=/api/1.0/brands/**, /api/1.0/categories/**, /v3/api-docs/category-brand

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/1.0/coupon/**, /v3/api-docs/coupon

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/