version: '3.8'

services:
  brand-service-postgres:
    container_name: brand-service-postgres
    image: postgres:16
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=brandDB
    expose:
      - 9001
    volumes:
      - brand-volume:/var/lib/postgresql/data
volumes:
  brand-volume:
