server:
  port: ${SERVER_PORT:8100}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: cart-service
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:9100}/${DB_NAME:postgres}?binaryTransfer=true&reWriteBatchedInserts=true
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091}
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_URL:http://localhost:8180}/realms/microservice-auth
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://${eureka.instance.hostname}:8761/}eureka/



grpc:
  server:
    port: 7102

  client:
    upload-service:
      address: 'discovery:///upload-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    coupon-service:
      address: 'discovery:///coupon-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    product-service:
      address: 'discovery:///product-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    product-stock-service:
      address: 'discovery:///product-stock-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

