version: '3.8'

services:
  discount-service-postgres:
    container_name: discount-service-postgres
    image: postgres:16
    ports:
      - "9005:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountDB
    expose:
      - 9005
    volumes:
      - discount-volume:/var/lib/postgresql/data
volumes:
  discount-volume:
